---
title: "Practical1"
format: html
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(fields)
library(asbio)
library(MuMIn)
library(regclass)
library(knitr)
```

```{r}
df <- read.csv("NystedFarms.csv")

EIA <- read_csv("EIA.csv")

EIA <- EIA |>
  mutate(tidestate = as.factor(tidestate),
         density = count/area)
```

```{r}
# # first group the data by gridcodes and find the mean density for each cell
# newdata <- group_by(EIA, GridCode) |>
#   summarise(x.pos = first(x.pos), 
#             y.pos = first(y.pos), 
#             area = first(area), 
#             density = mean(density))
# 
# # pick a nice colour scheme
# col <- colorRampPalette(rev(rgb(c(231,117,27), 
#                                 c(41,112,158), 
#                                 c(138,179,119), 
#                                 max = 255)))(100)
# 
# # plot the data
# p <- ggplot(newdata)
# p <- p + 
#   geom_tile(aes(x = x.pos, y = y.pos, fill = density, 
#                 height = 1000, width = 1000)) + 
#   scale_fill_gradientn(colours = col, space = "Lab", 
#                        na.value = "grey50", guide = "colourbar")
# p + theme_bw() + coord_equal()
```

Checking linearity:

exploratory plots

```{r}
# EIA |>
#   ggplot(aes(x = density)) +
#   geom_histogram(binwidth = 5) +
#   facet_grid(~ tidestate) +
#   theme_bw() +
#   labs(x = "Tide State", y = "Density")
# 
# EIA|>
#   ggplot(aes(y = density, x = observationhour)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "Observation Hour", y = "Density") +
#   scale_x_continuous(breaks = seq(0, 24, 1))
# 
# EIA|>
#   ggplot(aes(y = density, x = DayOfMonth)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "Day of Month", y = "Density") +
#   scale_x_continuous(breaks = seq(1, 31, 3))
# 
# EIA|>
#   ggplot(aes(y = density, x = MonthOfYear)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "Month of Year", y = "Density") +
#   scale_x_continuous(breaks = seq(1, 12, 1))
# 
# EIA|>
#   ggplot(aes(x = density)) +
#   geom_histogram(binwidth = 5) +
#   facet_grid(~ impact) +
#   theme_bw() +
#   labs(x = "Impact", y = "Density")
# 
# EIA|>
#   ggplot(aes(y = density, x = Year)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "Year", y = "Density") 
# 
# EIA|>
#   ggplot(aes(y = density, x = x.pos)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "X Coordinate", y = "Density")
# 
# EIA|>
#   ggplot(aes(y = density, x = y.pos)) +
#   geom_point() +
#   theme_bw() +
#   labs(x = "Y Coordinate", y = "Density")
```

```{r}
# workingModel <- 
#   lm(density ~ x.pos + y.pos + tidestate +
#        Year + DayOfMonth + MonthOfYear, data = EIA)
# 
# # par(mfrow=c(3,2))
# # 
# # termplot(workingModel,se=T, partial.resid = T)
# 
# summary(workingModel)
```


```{r}
# month as continuous
fit.full <- lm(density ~ tidestate + observationhour + DayOfMonth + MonthOfYear + impact + Year + x.pos + y.pos, 
               data = EIA)
summary(fit.full)
AIC(fit.full)

# month as a factor
fit.full.fac <- lm(density ~ tidestate + observationhour + DayOfMonth + as.factor(MonthOfYear) + impact + Year + x.pos + y.pos, data = EIA)
summary(fit.full.fac)
AIC(fit.full.fac)
VIF(fit.full.fac)
```

```{r}
fit.fullfac.noyr <- update(fit.full.fac, .~. - Year)
summary(fit.fullfac.noyr)
fit.fullfac.noimp <- update(fit.full.fac, .~. - impact)
summary(fit.fullfac.noimp)
AIC(fit.full, fit.full.fac, fit.fullfac.noimp, fit.fullfac.noyr)
```

```{r}
fit.interac <- update(fit.fullfac.noimp, .~. + Year*x.pos + Year*y.pos)

summary(fit.interac)
```

```{r}
dredge(fit.interac, options(na.action = 'na.fail'))
```

```{r}
step(fit.interac, direction = "both")
```


```{r}
n <- nrow(EIA)
step(fit.interac, direction = "both", k = log(n))
```

```{r}
AIC_selected_mod <- lm(density ~ tidestate + observationhour + as.factor(MonthOfYear) + Year + x.pos + y.pos + Year:x.pos, data = EIA)

summary <- summary(AIC_selected_mod)

# str(summary(AIC_selected_mod))

sum((fitted(AIC_selected_mod) - EIA$density)^2) / 27779

summary$sigma^2
```


```{r}
# Anova()
```

## GLS

```{r, message=F}
library(nlme)

EIA$sqrtdensity <- sqrt(EIA$density)

fit.gls <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos + y.pos + MonthOfYear + impact:x.pos + impact:y.pos, data = EIA, method = 'ML')
```

```{r}
# plot(fitted(fit.gls.exp), residuals(fit.gls.exp, type = 'response'))
# 
# cut.fit <- cut(fitted(fit.gls.exp), breaks = quantile(fitted(fit.gls.exp), probs = seq(0, 1, length = 20)))
# means1 <- tapply(fitted(fit.gls.exp), cut.fit, mean)
```

```{r}
# workingModel_GLS<- gls(sqrt(density) ~
#                          tidestate + observationhour + impact + x.pos + y.pos +
#                          MonthOfYear + impact:x.pos + impact:y.pos,
#                        data = EIA, weights=varExp(), method="ML")
# 
# cut.fit <- cut(
#   fitted(workingModel_GLS), 
#   breaks = quantile(fitted(workingModel_GLS), 
#   probs = seq(0, 1, length = 20))
# )
```


```{r}
EIA$sqrtdensity <- sqrt(EIA$density)
fit.gls.exp <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos + y.pos + MonthOfYear + impact:x.pos + impact:y.pos, 
                   data = EIA, 
                   method = 'ML', 
                   weights = varExp()
                )
# plot(fit.gls.exp)
# plot(fitted(fit.gls.exp), residuals(fit.gls.exp, type = 'response'))

cut.fit <- cut(
  fitted(fit.gls.exp), 
  breaks = quantile(fitted(fit.gls.exp), 
  probs = seq(0, 1, length = 20))
)
means1 <- tapply(fitted(fit.gls.exp), cut.fit, mean)

vars1 <- tapply(residuals(fit.gls.exp, type = "response"), cut.fit, var)

fitted1 <- (summary(fit.gls.exp)$sigma^2) * exp(2*coef(fit.gls.exp$model) * means1)

df1<-data.frame(means1,vars1,fitted1)

colnames(df1)=c("Means","Vars","Fitted")

```

```{r}
ggplot(df1, aes(x=Means, y=Vars)) +
  geom_point() +
  geom_line(aes(Means,Fitted),color="blue") + 
  theme_bw() +
  labs(x = "Fitted Values", 
       y = "Variance of Residuals", 
       title = "Observed vs Expected Mean Variance Relationship",
       caption = "Blue curve represents expected mean-variance relationship by the model, points represent observed mean-variance.")
  
```

# last section

```{r}
par(mfrow = c(1,2))
acf(residuals(fit.gls.exp, type = 'response'))
acf(residuals(fit.gls.exp, type = 'normalized'))
par(mfrow = c(1,1))
```
```{r}
EIA$block <- paste(EIA$Year, EIA$MonthOfYear, EIA$DayOfMonth, EIA$GridCode, sep = '')
library(dplyr)
EIA2 <- arrange(EIA, block, Year, MonthOfYear, DayOfMonth, GridCode)
```

```{r}
fit.gls.AR1 <- gls(sqrtdensity ~ 
                    tidestate + observationhour + impact + x.pos + y.pos + 
                    MonthOfYear + impact:x.pos + impact:y.pos, 
                    data = EIA2, 
                    method = 'ML', 
                    weights = varExp(),
                    correlation = corAR1(form = ~ 1 | block))
                   
```

```{r}
fit.gls.AR2 <- gls(sqrtdensity ~ 
                    tidestate + observationhour + impact + x.pos + y.pos + 
                    MonthOfYear + impact:x.pos + impact:y.pos, 
                    data = EIA2, 
                    method = 'ML', 
                    weights = varExp(),
                    correlation = corARMA(p = 2, q = 0, form = ~ 1 | block))
```

```{r}
AIC(fit.gls.AR1)

AIC(fit.gls.AR2)

acf(residuals(fit.gls.AR1, type = 'response'))
acf(residuals(fit.gls.AR1, type = 'normalized'))

acf(residuals(fit.gls.AR2, type = 'response'))
acf(residuals(fit.gls.AR2, type = 'normalized'))
```

```{r}
# Full Model
full_model <- fit.gls.AR2

anova(full_model)

# Model 1: Remove the least significant term (e.g., impact:y.pos)
model_1 <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos + y.pos + 
                 MonthOfYear + impact:x.pos, 
               data = EIA2, 
               method = 'ML', 
               weights = varExp(),
               correlation = corARMA(p = 2, q = 0, form = ~ 1 | block))

anova(full_model, model_1)
```

```{r}
model_2 <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos + 
                 MonthOfYear + impact:x.pos, 
               data = EIA2, 
               method = 'ML', 
               weights = varExp(),
               correlation = corARMA(p = 2, q = 0, form = ~ 1 | block))

anova(model_2)

anova(model_1, model_2)
```

```{r}
model_3 <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos + impact:x.pos, 
               data = EIA2, 
               method = 'ML', 
               weights = varExp(),
               correlation = corARMA(p = 2, q = 0, form = ~ 1 | block))

anova(model_3)

anova(model_2, model_3)
```

```{r}
model_4 <- gls(sqrtdensity ~ tidestate + observationhour + impact + x.pos, 
               data = EIA2, 
               method = 'ML', 
               weights = varExp(),
               correlation = corARMA(p = 2, q = 0, form = ~ 1 | block))

# c <- model_4$coefficients
# c
# before_construction <- (c[1] + c[4]*mean(EIA$observationhour) + c[6]*mean(EIA$x.pos))^2
# after_construction <- (c[1] + c[4]*mean(EIA$observationhour) + c[5] + c[6]*mean(EIA$x.pos))^2
# 
# d <- data.frame(
#   'Before Construction'= unname(before_construction),
#   'After Construction'= unname(after_construction)
# )
# 
# kable(d, digits = 3)

summary(model_4)

anova(model_4)

anova(model_3, model_4)
```

```{r}
pred_data <- data.frame(
  tidestate = c("SLACK", "SLACK"),
  observationhour = c(10, 10),
  MonthOfYear = c(6, 6),
  x.pos = c(1500, 1500),
  y.pos = c(1000, 1000),
  impact = c(0, 1)
) |>
  mutate(tidestate = factor(tidestate, levels = levels(EIA2$tidestate)))

myprediction <- MuMIn:::predict.gls(model_4, newdata = pred_data, se.fit = TRUE)


tbl <- tibble(
  Construction = c("Before", "After"),
  Estimate = myprediction$fit^2,
  Lower_Bound = (myprediction$fit - 1.96 * myprediction$se.fit)^2,
  Upper_Bound = (myprediction$fit + 1.96 * myprediction$se.fit)^2
) |>
  mutate(`95% Confidence Interval` = paste0("(", round(Lower_Bound, 3), ", ", round(Upper_Bound, 3), ")")) |>
  select(Construction, Estimate, `95% Confidence Interval`)

kable(tbl, digits = 3, align = "l")
```


```{r}
# Create a data frame for prediction
# Note: observationhour must be numeric, and tidestate must be a factor level
predict_data <- data.frame(
  tidestate = factor(c("SLACK", "SLACK"), levels = levels(EIA2$tidestate)),
  observationhour = c(10, 10),
  x.pos = c(1500, 1500),
  impact = c(0, 0)
)

# Predict on the square-root scale
sqrt_pred <- MuMIn:::predict.gls(model_4, newdata = predict_data)

myprediction <- MuMIn:::predict.gls(model_4, newdata = predict_data, 
                                    se.fit = TRUE, interval = "confidence", level = 0.95)
```

```{r}
se1 <- 1.96*myprediction$se.fit[1]
se2 <- 1.96*myprediction$se.fit[2]

lower1 <- myprediction$fit[1] - se1
upper1 <- myprediction$fit[1] + se1

lower2 <- myprediction$fit[2] - se2
upper2 <- myprediction$fit[2] + se2
```




